### PR TITLE
Modified to use the arial font.

### PR DESCRIPTION
**Pull request by zongyan**
This commit provides a solution to utilise the Arial font, which is also recommended by the Graduate School. If you would like to adopt this font, please use the XeLaTex engine.

### CODE REVIEW

**Comment by gcoulby** [comment]
I don't really want to do this, due to the additional engines. If you want to make specific customisations I recommend forking the project.

**Comment by zongyan** [comment]
I just want to provide an alternative solution of changing the font in the thesis. If you need more customisation of your thesis, please redirect to https://github.com/zongyan/nu_thesis_template

**Comment by gcoulby** [comment]
Hi Zongyan. 

Firstly, thank you for providing updates. It is really appreciated. 

I understand what you were aiming for. However, this template was supposed to act as a barebones template that people can customise how they want according to faculty/departmental guidelines etc. 

I have customised my README to provide a link to your fork for those that would like the additional customisations. 

Please also consider checking your modifications work on Overleaf and publishing your changes there. Most of the users that use this template use the version published on overleaf.

**Comment by zongyan** [comment]
Many thanks. Once I have done all customisations, I will upload the modified version to Overleaf.

**Pull request closed without merging**
